[package]
name = "zeroconf-service-example"
version = "0.1.0"
authors = ["Walker Crouse <walkercrouse@hotmail.com>"]
edition = "2024"

[dependencies]
zeroconf = { path = "../../zeroconf" }
env_logger = "0.10.0"
log = "0.4.20"
clap = { version = "4.4.4", features = ["derive"] }
